### ISSUE TITLE
Create IAM role and policy to use on Concourse when running terraform.

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform-test-cluster-env#1]
## Background:

Concourse jobs will require various levels of AWS access when running.  We decided the best way to achieve this access was to use IAM Roles and policies. 

I forgot to capture what the minimum policies that were required during the planning session. 

## Questions:

Need an answer before starting

- Do the TF creation templates live in their own repo?
 
If the answer is 'Yes', then add these steps to 'Done When', below:
- [ ] Create a public github repo `cloud-platform-concourse-roles-and-policies` 
- [ ] Add webops as an admin collaboration group to that repo.

## Done When:  

- [ ] The minimum required policies are defined and documented (check with @kerin). 
- [ ] Policy creation is templated in Terraform including documentation on running the template
- [ ] Role creation is templated in Terraform including documentation on running the template
- [ ] Role is created on AWS
- [ ] The policies are associated with that role
- [ ] The policies have been tested and shown to run against something very, very simple (the S3 uploader demo, for example).

**Comment by tatyree** [comment]
I don't have admin access on this repo yet, so I can't create labels.  Estimate: 3

**Comment by kalbir** [comment]
Closed as replaced with the stories in ministryofjustice/cloud-platform#62.
