### ISSUE TITLE
Create a Concourse pipeline for Terraform Resources

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform-test-cluster-env#2]
## Dependencies:
https://github.com/ministryofjustice/cloud-platform-test-cluster-env/issues/1

## Background:
We need a pipeline to handle TF resources in the Concourse pipeline.

## Done When:
- [ ] End user adds TF as part of their namespace (for the purposes of testing, TF should provision an S3 bucket). 
- [ ] Pipeline picks up this TF and executes it to provision the resource
- [ ] This workflow is tested (discuss with @kerin or Mitch as to how that might be done)
- [ ] Workflow is signed off by one of the team leads

**Comment by kalbir** [comment]
From our discussion, this pipeline would take the terraform that the user has added as part of their namespace to e.g. define their S3 bucket and would execute that to provision the AWS resources.

**Comment by kalbir** [comment]
Closed as replaced with the stories in ministryofjustice/cloud-platform#62.
