### ISSUE TITLE
Build parent pipeline that runs the TF resources pipeline and the environment pipeline.

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform-test-cluster-env#4]
**Background**
The other two pipeline need to be triggered in order.  This pipeline will be that trigger.

**Done when**
- [ ] The parent pipeline exists (does it needs its own repo?) 
- [ ] The parent pipeline can be triggered as need (TBD)
- [ ] The parent pipeline triggers the child pipelines in the correct order
- [ ] The parent pipeline fails with appropriate alerts if either child fails
- [ ] The parent pipeline notifies appropriately on success.
- [ ] The workflow has been signed off by Kalbir, Kerin, Mitch or Todd. 

**Dependencies**
* https://github.com/ministryofjustice/cloud-platform-test-cluster-env/issues/1
* https://github.com/ministryofjustice/cloud-platform-test-cluster-env/issues/2
* https://github.com/ministryofjustice/cloud-platform-test-cluster-env/issues/3

**Estimate**
3

**Comment by tatyree** [comment]
I'm concerned this might be more complex than we initially thought owing to the need to bubble up failures.  @kerin do you know if this is something that Concourse does automatically?

**Comment by kalbir** [comment]
Closed as replaced with the stories in ministryofjustice/cloud-platform#62.
