### ISSUE TITLE
Notifications on build successes and failures

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform-test-cluster-env#5]
**Background**
We want to be notified when builds succeed or fail.  

**Done when**
For each build (and for each pipeline?) 
- [ ] A notification is sent to slack on success 
- [ ] A notification is sent to slack on failure
- [ ]  The workflow has been signed off by Kalbir, Kerin, Mitch or Todd.

**Comment by tatyree** [comment]
@kerin does this need to work for each pipeline, or is it sufficient that the parent sends the notification?

**Comment by kalbir** [comment]
Closed and replaced by the stories in https://github.com/ministryofjustice/cloud-platform/issues/62, in particular https://github.com/ministryofjustice/cloud-platform/issues/38 and https://github.com/ministryofjustice/cloud-platform/issues/74
