### ISSUE TITLE
Kerin to decide how to do role names.

### ISSUE THREAD

**Issue by tatyree** [ministryofjustice/cloud-platform-test-cluster-env#6]
**Background**
Naming things is hard.  Kerin is going to ponder and document how role names should be handled. 

**Done when**
- [ ] Kerin has made a decision
- [ ] Kerin has document and disseminated that decision :)

**Comment by kalbir** [comment]
Closed as replaced with the stories in https://github.com/ministryofjustice/cloud-platform/issues/62.
